from datetime import datetime
from decimal import Decimal
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, Field

from app.models.enums import PaymentMethod
from app.modules.catalog.schemas import CategoryRead, DepartmentRead, PriceRead, ProductRead, StockRead
from app.modules.sales.schemas import OrderItemCreate

# ---------------------------------------------------------------------
# push (mobile -> server): batch of sales made offline
# ---------------------------------------------------------------------


class SyncSaleCreate(BaseModel):
    """One offline sale from the mobile app's pending queue. client_reference is the
    idempotency key (generated by the app at sale time); occurred_at is required here
    (unlike the online OrderCreate) because a synced sale is meaningless without it —
    it's the whole reason this field exists."""

    client_reference: UUID
    client_id: int
    payment_method: PaymentMethod
    discount: Decimal = Field(default=Decimal("0"), ge=0)
    occurred_at: datetime
    items: list[OrderItemCreate] = Field(min_length=1)


class PushRequest(BaseModel):
    sales: list[SyncSaleCreate] = Field(min_length=1)


class PushResultItem(BaseModel):
    client_reference: UUID
    status: Literal["created", "duplicate", "rejected"]
    order_id: int | None = None
    reason: str | None = None


class PushResponse(BaseModel):
    results: list[PushResultItem]


# ---------------------------------------------------------------------
# pull (server -> mobile): catalog delta since last sync
# ---------------------------------------------------------------------


class PullResponse(BaseModel):
    synced_at: datetime
    departments: list[DepartmentRead]
    categories: list[CategoryRead]
    products: list[ProductRead]
    prices: list[PriceRead]
    stocks: list[StockRead]
